categories = {'american_gothic_parody',...
                'arnolfinis_wedding_parody',...
                'birth_of_venus_parody',...
                'death_of_marat_parody',...
                'girl_with_a_pearl_earring_parody',...
                'las_meninas_parody',...
                'last_supper_parody',...
                'melting_watches_the_persistence_of_memory_parody',...
                'mona_lisa_parody',...
                'munch_scream_parody',...
                'seurat_sundey_afternoon_on_la_grande_jatte_parody'};
            
project_path = '/Users/yigitozgumus/Desktop/Cmpe492/CmpE492Final/Cmpe 492-Matlab/Classifier-mark1';
imgSets = [ imageSet(fullfile('/Users/yigitozgumus/Desktop/Cmpe492/CmpE492Final/Cmpe 492-Matlab/Classifier-mark1/data', 'american_gothic_parody')), ...
 imageSet(fullfile('/Users/yigitozgumus/Desktop/Cmpe492/CmpE492Final/Cmpe 492-Matlab/Classifier-mark1/data', 'arnolfinis_wedding_parody')), ...
 imageSet(fullfile('/Users/yigitozgumus/Desktop/Cmpe492/CmpE492Final/Cmpe 492-Matlab/Classifier-mark1/data', 'birth_of_venus_parody')), ...
 imageSet(fullfile('/Users/yigitozgumus/Desktop/Cmpe492/CmpE492Final/Cmpe 492-Matlab/Classifier-mark1/data',  'death_of_marat_parody')), ...
 imageSet(fullfile('/Users/yigitozgumus/Desktop/Cmpe492/CmpE492Final/Cmpe 492-Matlab/Classifier-mark1/data',  'girl_with_a_pearl_earring_parody')), ...
 imageSet(fullfile('/Users/yigitozgumus/Desktop/Cmpe492/CmpE492Final/Cmpe 492-Matlab/Classifier-mark1/data',  'las_meninas_parody')), ...
 imageSet(fullfile('/Users/yigitozgumus/Desktop/Cmpe492/CmpE492Final/Cmpe 492-Matlab/Classifier-mark1/data',  'last_supper_parody')), ...
 imageSet(fullfile('/Users/yigitozgumus/Desktop/Cmpe492/CmpE492Final/Cmpe 492-Matlab/Classifier-mark1/data', 'melting_watches_the_persistence_of_memory_parody')), ...
 imageSet(fullfile('/Users/yigitozgumus/Desktop/Cmpe492/CmpE492Final/Cmpe 492-Matlab/Classifier-mark1/data',  'mona_lisa_parody')), ...
 imageSet(fullfile('/Users/yigitozgumus/Desktop/Cmpe492/CmpE492Final/Cmpe 492-Matlab/Classifier-mark1/data', 'seurat_sundey_afternoon_on_la_grande_jatte_parody')) ]; 

% determine the smallest amount of images in a category
minSetCount = min([imgSets.Count]);

% Use partition method to trim the set.
imgSets = partition(imgSets,minSetCount,'randomize');

[trainingSets, validationSets] = partition(imgSets, 0.3, 'randomize');
[trainingSets_m2, validationSets_m2] = partition(imgSets, 0.7, 'randomize');
extractor = @getHogFeatures;
bag_hog = bagOfFeatures(trainingSets, 'CustomExtractor',extractor);
bag = bagOfFeatures(trainingSets);


categoryClassifier = trainImageCategoryClassifier(trainingSets, bag);
categoryClassifier_hog = trainImageCategoryClassifier(trainingSets, bag_hog);
confMatrix_training = evaluate(categoryClassifier, trainingSets);
confMatrix_validation = evaluate(categoryClassifier, validationSets);

confMatrix_training_hog = evaluate(categoryClassifier_hog, trainingSets);
confMatrix_validation_hog = evaluate(categoryClassifier_hog, validationSets);

% Compute average accuracy
accuracy_surf = mean(diag(confMatrix_validation));
accuracy_hog = mean(diag(confMatrix_validation_hog));

categoryClassifier_m2 = trainImageCategoryClassifier(trainingSets_m2, bag);
categoryClassifier_hog_m2 = trainImageCategoryClassifier(trainingSets_m2, bag_hog);
%imds = imageDatastore(fullfile('/Users/yigitozgumus/Desktop/Cmpe492/CmpE492Final/Cmpe 492-Matlab/Classifier-mark1/data',categories), 'LabelSource', 'foldernames');
%tbl = countEachLabel(imds);
%minSetCount = min(tbl{:,2}); % determine the smallest amount of images in a category
% Use splitEachLabel method to trim the set.
%imds = splitEachLabel(imds, minSetCount, 'randomize');

% Notice that each set now has exactly the same number of images.
%countEachLabel(imds)

%[trainingSet, validationSet] = splitEachLabel(imds, 0.3, 'randomize');

%bag = bagOfFeatures(trainingSet);